hq_superset/hq_domain.py
Base branch is **sr/mdomain**.
Only replaces tabs with spaces.
=> Convert tabs to spaces

hq_superset/hq_domain.py, hq_superset/oauth.py, hq_superset/views.py
@akashkj   @kaapstorm  @proteusvacuum
=> Handle failures at HQ end

hq_superset/oauth.py, hq_superset/templates/tail_js_custom_extra.html
Fixes https://dimagi-dev.atlassian.net/browse/QA-4302 
Requires HQ change https://github.com/dimagi/commcare-hq/pull/31883
@kaapstorm @Charl1996
=> On login filter domains to where user can view reports

README.md, hq_superset/templates/select_domain.html
=> More details on README

hq_superset/templates/hq_datasource_list.html, hq_superset/views.py, setup.py
=> Store HQ name in the descrption column and Use dimagi-superset package

hq_superset/tests/test_utils.py, hq_superset/utils.py
https://dimagi-dev.atlassian.net/browse/SC-2306
=> Fix bugs related to pandas data type detection

apache-superset.md
I forgot to commit this file in PR https://github.com/dimagi/hq_superset/pull/12/files
=> Add docs on superset fork maintenanace

setup.py, superset_config.example.py
https://sentry.io/organizations/dimagi/issues/?environment=demo&project=4504450653159424
=> Add sentry integration

hq_superset/views.py
@SmittieC I am going to try this to see if it fixes the 504 for large CSVs https://dimagi-dev.atlassian.net/browse/SC-2596
=> Process chunks separately

README.md
Changes pulled from the `nh/webhook` branch, as mentioned on Slack.
Mostly added setup instructions. Also tweaked some spelling, and added some line breaks for easier reading as plaintext.
=> Updates and tweaks to README.md

README.md
Important documentation was hidden in plain sight. This addition to README.md is an attempt to bring it into the light.
=> Point people as blind as me to apache-superset.md

apache-superset.md
Updates documentation with recent lessons learned.
(Documentation-only changes.)
=> Update `apache-superset.md` docs

README.md
Tweaks documentation with OAuth application settings in CommCare HQ, and explicit user type.
Are these the settings that you used @mkangia ?
=> Add OAuth application settings

hq_superset/__init__.py, hq_superset/exceptions.py, hq_superset/oauth.py, hq_superset/services.py, hq_superset/tasks.py, hq_superset/templates/hq_datasource_list.html, hq_superset/tests/base_test.py, hq_superset/tests/test_oauth.py, hq_superset/tests/test_views.py, hq_superset/tests/utils.py, hq_superset/utils.py, hq_superset/views.py, superset_config.example.py
This PR separates out the prefactor commits for PR #41 
These commits do not make any significant change to functionality. They just clean up code a little.
Easiest to review by commit. :blowfish: :tropical_fish: :fish: :shark: :dolphin:
=> Prefactor for background sync

README.md, hq_superset/templates/hq_datasource_list.html, hq_superset/templates/tail_js_custom_extra.html
https://dimagi.atlassian.net/browse/SC-3446
Adapt to superset changes version 2 to version 3.
1. Satisfy [CSP requirements](https://superset.apache.org/docs/security/#content-security-policy-csp) for the inline script
2. Update url for viewing imported data source
3. Unrelated minor text change from "log in in" to "log in"
=> Superset upgrade fixes

.github/workflows/tests.yml, hq_superset/hq_requests.py, hq_superset/services.py, hq_superset/tests/test_views.py, hq_superset/views.py, setup.py
Review by commit.
https://dimagi.atlassian.net/browse/SC-3684
=> Notify user about failure to refresh datasource

setup.py
Since last deployed code on commcare analytics prod, two more changes have been done.
https://github.com/dimagi/commcare-analytics/pull/46
https://github.com/dimagi/commcare-analytics/pull/47
Bumping the version up so we can track the releases better.
=> upgrade version for release

setup.py
This is simply updating the version for the new release that will happen once this PR is merged.
=> Update version for new release

setup.py
Update major version to `1.0.0` since it's technically a "breaking change" from the previous one (the authentication works fundamentally different now)
=> Update major version

hq_superset/hq_requests.py, hq_superset/tests/test_hq_request.py
Tiny change.
Test to follow shortly.
=> Use urljoin to add a slash if necessary

scripts/staging.yml
Add [branch](https://github.com/dimagi/commcare-analytics/pull/84) to staging for testing
=> Add branch to staging

scripts/staging.yml
Removing feature branch from staging since it's merged now.
=> Remove branch from staging

setup.py, superset_config.example.py
This PR adds a new dependency and code in the Superset config so that Redis can be patched for monitoring in DataDog.
=> Redis Integration

setup.py
To release
https://github.com/dimagi/commcare-analytics/pull/95
=> Bump version 1.1.2

scripts/staging.yml
=> Add feature to staging

.github/workflows/tests.yml, README.md, requirements_test.txt, setup.py
A few small tweaks to `setup.py`
:blowfish:
=> Tweaks to `setup.py`

scripts/staging.yml
I've commented out some branches from staging since CCA is behaving very strange and I can't access the site. I want to eliminate all potential influences for now.
=> Comment out branches

scripts/staging.yml
@kaapstorm I commented out your branch from staging because there was some issues with it. It's back now with this PR.
=> Remove branch from staging.yml

scripts/staging.yml
Just removing a branch from staging.
@kaapstorm What is the `nh/test_maps` branch for?
=> Remove branch

apache-superset.md
Simply some documentation updates regarding the upgrade process.
=> Make some documentation updates
