hq_superset/oauth.py

On Signup, FAB only stores access_token into flask session (see [code](https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/security/manager.py#L552)). This is enough for signup only OAuth integrations, but integrations needing to access Oauth endpoints at a latter point need the refresh_token as well to refresh the access token. This PR stores the full oauth response on the server side session (which is encrypted).
@akashkj @proteusvacuum @kaapstorm

Track full Oauth response in the session

---

hq_superset/utils.py
hq_superset/views.py

[Ticket](https://dimagi-dev.atlassian.net/browse/SC-2208)
Handle datasource array datatype. Arrays will be stored in postgres as a collection of strings. I'm not sure if we can assume that it will always be strings?
As far as testing goes, I could pull the data from postgres through SQL Lab in superset and view it. Not sure if there is other tests I can also do?

Handle array datatype columns in datasets

---

hq_superset/tasks.py

I have noticed that the datasource csv files aren't getting deleted after async import. This one deletes so that the files don't build up.
@kaapstorm @Charl1996

Remove datasource file after task success as well

---

.github/workflows/tests.yml
hq_superset/__init__.py
hq_superset/hq_domain.py
hq_superset/oauth.py
hq_superset/tasks.py
hq_superset/tests/base_test.py
hq_superset/tests/test_hq_domain.py
hq_superset/tests/test_oauth.py
hq_superset/tests/test_utils.py
hq_superset/tests/test_views.py
hq_superset/tests/utils.py
hq_superset/utils.py
hq_superset/views.py
requirements_test.txt
setup.py

Upgrades hq_superset to apache-superset==3.1.0
This required a few tweaks:
* `superset.dataset.commands` moved to `superset.commands.dataset`
* `is_user_admin()` became `security_manager.is_admin()`
* `get_sqla_engine()` method became `get_sqla_engine_with_context()` context manager.
* The parameters of a couple of commands changed
That was about it.

Upgrade to apache-superset==3.1.0

---

hq_superset/__init__.py
hq_superset/tests/base_test.py
hq_superset/tests/config_for_tests.py
superset_config.example.py

This change uses the `SUPERSET_CONFIG_PATH` environment variable to manage Superset configuration, both for tests and for normal operation.
Calling `hq_superset.patch_superset_config(superset_config)` is unnecessary. The same can be achieved by including 
```
FLASK_APP_MUTATOR = flask_app_mutator
CUSTOM_SECURITY_MANAGER = oauth.CommCareSecurityManager
```
in the config file.
I've added a comment to the start of `superset_config.example.py` to explain how to set the environment variable for normal operation. The environment variable is set automatically in `hq_superset/tests/base_test.py` for running tests.

Use `SUPERSET_CONFIG_PATH` env var to manage config

---

setup.py

Updates package requirements to use Dimagi Superset instead of Apache Superset.

Use dimagi-superset 3.1.0

---

README.md
hq_superset/__init__.py
hq_superset/api.py
hq_superset/const.py
hq_superset/exceptions.py
hq_superset/hq_domain.py
hq_superset/hq_requests.py
hq_superset/hq_url.py
hq_superset/migrations/README
hq_superset/migrations/alembic.ini
hq_superset/migrations/env.py
hq_superset/migrations/script.py.mako
hq_superset/migrations/versions/2024-02-24_23-53_56d0467ff6ff_added_oauth_tables.py
hq_superset/models.py
hq_superset/oauth2_server.py
hq_superset/services.py
hq_superset/tasks.py
hq_superset/tests/base_test.py
hq_superset/tests/config_for_tests.py
hq_superset/tests/const.py
hq_superset/tests/test_hq_domain.py
hq_superset/tests/test_utils.py
hq_superset/tests/test_views.py
hq_superset/utils.py
hq_superset/views.py
superset_config.example.py

Jira: [SC-3212](https://dimagi.atlassian.net/browse/SC-3212)
This pull request includes
* A series of small prefactor commits
* A large commit that adds an API endpoint for accepting dataset change requests from CommCare HQ
* A large commit that adds an OAuth 2.0 server for authenticating incoming requests
* A migration for adding the models for the OAuth 2.0 server
Easiest to review :blowfish: commit :octopus: by :tropical_fish: commit :fish: 
This code has been tested locally.
It will be deployed to Staging on Wed Feb 28.
QA is scheduled.

Background sync for datasets from CommCare HQ

---

hq_superset/services.py
hq_superset/tasks.py
hq_superset/tests/test_views.py
hq_superset/views.py

https://dimagi.atlassian.net/browse/SC-3646
We were retaining files in case the task fails.
Also reached out to @sravfeyn to confirm this change does not cause unexpected issues [here](https://github.com/dimagi/commcare-analytics/pull/28/files#r1618328156)
The other [place](https://github.com/dimagi/commcare-analytics/blob/bd46e6e7d590879c7934224d2d729227c5fe0b04/hq_superset/services.py#L155) mentioned in the [ticket](https://dimagi.atlassian.net/browse/SC-3646?focusedCommentId=328631) should be handled by this change itself because the exception raised is caught in `refresh_hq_datasource_task` after that.

Delete downloaded files in case of exception as well

---

hq_superset/utils.py

Avoids an error caused when trying to cast `None` as a Python datetime. This can happen when a data source has a null value in a datetime/TIMESTAMP column.
This change is covered by doctests.

Allow TIMESTAMP values to be None or empty

---

hq_superset/oauth2_server.py

Drops token expiry. This is intended to reduce performance problems under a high volume of incoming requests.

Tokens do not expire

---

.gitignore
hq_superset/hq_url.py
hq_superset/services.py
hq_superset/tests/test_views.py
hq_superset/views.py

[Ticket](https://dimagi.atlassian.net/browse/SC-3772)
This PR implements the final step to unsubscribe a data source from sending updates to a CCA instance when a user removes a data source on CCA.

Unsubscribe data source on dataset delete

---

hq_superset/api.py

This PR simply returns a 404 status code with a message saying the data source is missing when the data source is removed on CCA but the repeater still sends updates to CCA. 
There's a spec open for review for properly handling removed data sources on CCA and its corresponding repeater on HQ.

Return 404 on missing table

---

hq_superset/api.py
hq_superset/tasks.py

In order to make the update dataset request as fast as possible so it can keep up with the load of requests received from HQ, move the actual update to a background task via celery

Make data source update async

---

hq_superset/models.py
hq_superset/oauth2_server.py

Each time a CommCareHQ repeater sends a request to CCA, it requests a new token.
On CCA, when we were generating a new token, we would revoke all old ones for that client.
In case of concurrent requests by repeaters one new token revokes the other one yet to be used, which lead to authorization errors.
So,
we are skipping revoking tokens when generating new tokens.
The expiry time was removed as a part of this investigation and is now added back but with a much shorter time of 10 seconds.
As a follow up, 
we will clean up expired tokens via a celery task and/or not need to get a new token for each repeat record.

Skip revoking tokens

---

hq_superset/oauth2_server.py
superset_config.example.py

This turns out to be the core of the issue/misunderstanding that we have been seeing.
When we modified the value for [expiry to 0](https://github.com/dimagi/commcare-analytics/commit/d860f896d566e335967bccafdad52b5363cdec6c) it didn't really take effect.
The token that was sent back in response to HQ, is the one that was passed to the function `save_token` and is expected to be stored as it is, though we were modifying it here which would lead to a mismatch in what HQ was told about the token and what we stored. So, a token even if valid according to HQ could be expired as per CommCareAnalytics or vice versa.
This didn't cause any mismatch back then because it set the default value of 1 day which was also the value set for expiry for the token. And HQ was requesting a new token for every …

Store expiry correctly

---

apache-superset.md

Minor readme updates regarding using version numbers for PyPi

Readme update related to pypi

---

setup.py

Simply upgrades dimagi superset version to the latest `3.1.0.post1`.
This new version includes the new ivory-cost country map that was included in [this PR](https://github.com/dimagi/superset/pull/2).

Upgrade dimagi superset version

---

README.md
scripts/rebuildstaging
scripts/staging.yml
setup.py

This PR adds the ability for developers to more easily track and rebuild the CommCare Analytics staging branch. At the moment it's _very_ basic.
When you have a feature branch that you want to deploy to staging you should first add it to the `scripts/staging.yml` file under the `branches` section and run the command to rebuild the staging branch:
> ./scripts/rebuildstaging
Note that this will only rebuild the staging branch locally, so afterwards you need to push the staging branch and deploy CCA as we currently do - manually. 
Dimagi maintains a pypi package called [git-rebuild-branch](https://pypi.org/project/git-build-branch/) which this PR is also using. This PR lists it as a dev dependency in the `setup.py` file, so in order to use it the developer must first run
> pip install -e …

Rebuild staging branches script

---

superset_config.example.py

We added talisman config to superset setup.
This PR adds it to the example file.
Config shared with hints from how it is currently, as shared in https://github.com/dimagi/commcare-analytics-ansible/pull/31

Add talisman to example file

---

superset_config.example.py

It appears this task was either never there or now removed
from celery logs
```
Thw full contents of the message headers:
{'lang': 'py', 'task': 'email_reports.schedule_hourly', 'id': '2fd27c9c-ab86-46e9-b87d-a99d34a5b6aa', 'shadow': None, 'eta': N
one, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '2fd27c9c-ab86-4
6e9-b87d-a99d34a5b6aa', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen648994@ip-172-31-38-75', 'ignor
e_result': False}
The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
File "/home/ubuntu/www/.virtualenvs/superset/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 591, in 
on_task_received
strategy = …
```

Remove missing task

---

hq_superset/api.py
hq_superset/const.py
hq_superset/hq_domain.py
hq_superset/migrations/versions/2024-02-24_23-53_56d0467ff6ff_added_oauth_tables.py
hq_superset/models.py
hq_superset/oauth.py
hq_superset/oauth2_server.py
hq_superset/services.py
hq_superset/tasks.py
hq_superset/tests/base_test.py
hq_superset/tests/config_for_tests.py
hq_superset/tests/const.py
hq_superset/tests/test_hq_domain.py
hq_superset/tests/test_oauth.py
hq_superset/tests/test_utils.py
hq_superset/tests/test_views.py
hq_superset/tests/utils.py
hq_superset/utils.py
hq_superset/views.py
superset_config.example.py

https://dimagi.atlassian.net/browse/SC-3475
Building up on work done in cs/SC-3473-user-roles-from-hq to expire user permissions in an hour to keep permissions up to date with HQ.
Review by commit :fish: 
There is quite some refactor, done in separate commits for clarity
All tests ran locally successfully. They wont run here since base branch isn't master.
https://dimagi.atlassian.net/browse/QA-7205

Expire user permissions

---

superset_config.example.py

CommCare Ansible specifies [this database name](https://github.com/dimagi/commcare-analytics-ansible/blob/9e4216dcb2003072d901effa805243996e9cc2b9/environments/example/vars.yml#L12), so this PR is simply to rectify this repo's take on it.

Fix database name

---

README.md

This PR is updating the readme with the staging deploy steps as outlined [here](https://dimagi.atlassian.net/wiki/spaces/GS/pages/2144316885/CommCare+Analytics+Deployment).
The reason for this is mainly so that whoever is reading the "Testing on staging" part in the readme don't have to search for an additional doc on how to deploy staging.

Update README with staging deploy steps

---

hq_superset/__init__.py
hq_superset/hq_domain.py
hq_superset/oauth.py
hq_superset/tests/test_views.py

[Ticket](https://dimagi.atlassian.net/browse/SC-4105)
We've been having an issue on CCA where users which are already logged in to CCA could not access the site due to a 500 error. The error can be seen below.
>  File "/home/ubuntu/www/.virtualenvs/superset/lib/python3.10/site-packages/hq_superset/utils.py", line 220, in _get_domain_access
response = hq_request.get()
File "/home/ubuntu/www/.virtualenvs/superset/lib/python3.10/site-packages/hq_superset/hq_requests.py", line 28, in get
return self.commcare_provider.get(self.url, token=self.oauth_token)
File "/home/ubuntu/www/.virtualenvs/superset/lib/python3.10/site-packages/hq_superset/hq_requests.py", line 13, in oauth_token
return get_valid_cchq_oauth_token()
File "/home/ubuntu/www/.virtualenvs/superset/lib/python3.10/site-packages/hq_sup …

Redirect user to login page when oauth session expired

---

hq_superset/tasks.py
hq_superset/tests/config_for_tests.py
hq_superset/tests/test_tasks.py
superset_config.example.py

https://dimagi.atlassian.net/browse/SC-4051

Add task to clean up shared files regularly

---

hq_superset/tasks.py
superset_config.example.py

As a follow up to https://github.com/dimagi/commcare-analytics/pull/90,
Register the task so it is discovered by celery
Tested
```
[2024-12-16 08:01:00,043: INFO/MainProcess] Task delete_redundant_shared_files[850a0b75-2d85-4760-a5cd-df77dc51baff] received
[2024-12-16 08:01:00,046: INFO/ForkPoolWorker-6] Task delete_redundant_shared_files[850a0b75-2d85-4760-a5cd-df77dc51baff] succeeded in 0.002176055684685707s: None
```

Register missing task

---

scripts/staging.yml

Simply removes a branch from the `staging.yml` file which is no longer needed.

Remove Branch from staging.yml

---

scripts/staging.yml

No rush on this one, because I lost patience and rebuilt the staging branch manually. :expressionless: 
But I was an idiot, and put the merge branch _after_ the conflicting branches, instead of _before_ them. This PR has the correct order.
I'm opening the PR so that `staging.yml` in master is an accurate reflection of what is deployed.

Fix order in staging.yml

---

scripts/staging.yml

Add branch to staging.yml.
The [feature branch](https://github.com/dimagi/commcare-analytics/compare/cs/SC-4275-add-moz-map?expand=1) will use the latest version of `dimagi/superset`, which has the mozambique country map added.

Update staging branches

---

setup.py

[Ticket](https://dimagi.atlassian.net/browse/SC-4275)
An new version of dimagi-superset is available with the `mozambique` country map added (see [change here](https://github.com/dimagi/superset/pull/4), although adding the map required me to follow [this guide](https://github.com/dimagi/commcare-analytics/blob/master/apache-superset.md#example-of-adding-a-new-customization), which does not make use of the `master` branch to track changes, but rather github tags - we need to consolidate the two, because it's confusing. [Here is a difference](https://github.com/dimagi/superset/compare/master...dimagi:superset:3.1.0-dimagi-4) between the latest tagged version and `master`).
This PR is to make use of the new version.
Please note that CCA staging already makes use of this new version of …

Use new version of dimagi-superset

---

hq_superset/hq_domain.py
superset_config.example.py

Link to ticket [here](https://dimagi.atlassian.net/browse/SC-4284).
This PR introduces a small change in which an extra check is added to the `after_request` handler for the Superset Flask application. This new hook essentially checks for 500 requests coming in from the `/api/v1/sqllab/execute/` endpoint which have a certain error type and changes them to 400.
The reason for this change is that SQLLab allows for creating invalid queries (e.g. accessing a table that doesn't exist). When this happens, Superset simply throws an unhandled 500 exception which then gets raised as a false-positive 500 request on Datadog. Changing the status code to 400 more appropriately flags it as simply an invalid request rather than an exception.
From a user's perspective nothing is changing and they will …

Error Handling for False-Positive SQLLab Exception
